## 
## hackademia
## 


application:
  # My app name
  name: fMRIprep
  # My app version (x.y.z)
  version: 
  # short description
  description: "fMRIprep."
  app:
    # image or module
    type: image
    # image path or module
    image:  docker://nipreps/fmriprep:24.1.1
    # cmd to launch in the container (ruby format)
    cmd: "fmriprep"
    arguments:
      # argument for the app
      bids_dir:
        widget: "path_selector"
        visible: True
        show_hidden: False
        show_files: False
        label: "bids_dir"
        help: "The root folder of a BIDS valid dataset."
      output_dir:
        widget: "path_selector"
        visible: True
        show_hidden: False
        show_files: False
        value: "~/scratch" # default, can be overwritten if visible: True
        label: "Working Directory"
        help: "The output path for the outcomes of preprocessing and visual reports."
      analysis_level:
        visible: False # use value if visible: False
        value: "participant"
      participant_label:
        widget: "text_field"
        visible: True
        command-line-flag: "--participant-label"
        label: "participant_label"
        help: "A space delimited list of participant identifiers or a single identifier."
        # required
        # help 
        # pattern 
        # min 
        # max 
        # step 
        # options 
        # cacheable 
        # display 
  apptainer:
      fakeroot: True
  slurm:
      auto_accounts: True
      auto_queues: True
  resources:
    wall_time: 3600 # TODO handle native slurm -> widgets, resources, native