## 
## hackademia
## 


application:
  # My app name
  name: Commodor_MachuPicchu
  # My app version (x.y.z)
  version: 
  # short description
  description: "A test application."
  app:
    # image or module
    type: image
    # image path or module
    image:  docker://docker/whalesay
    # cmd to launch in the container (ruby format)
    cmd: "cowsay #{input}"
    arguments:
      # argument for the app
      input:
        visible: True
        widget: "text_field"
        label: "Input File Name"
        help: "Where the data is coming from (relative to the working directory field above)." 
      output:
        visible: True
        widget: "text_field"
        label: "Output File Name"
        help: "Where the results will be going to (relative to the working directory field above)."
      # working directory to launch the app
      workdir:
        widget: "path_selector"
        show_hidden: true
        show_files: false
        command-line-flag: "-w"
        visible: True
        label: "Working Directory"
        help: "Select your project directory."
  apptainer:
      fakeroot: True
  slurm:
      auto_accounts: True
      auto_queues: True
      auto_primary_group: False
      bc_num_slots: False
      bc_email_on_started: True
  resources:
    # s
    estimated_run_time:
      value: 30
      visible: False
      label: "estimated_run_time"
      help: "estimated_run_time"
    # number of cores
    cpus:
      value: 1
      visible: False
      label: "cpus"
      help: "cpus"
    # ex: ampere:2,VramPerGpu:10G
    gpus:
      value: 0
      visible: False
      label: "gpus"
      help: "gpus"
    # RAM in GB
    ram:
      value: 1
      visible: False
      label: "ram"
      help: "ram"
    # parallel if more than 1
    nbtasks:
      value: 1
      visible: False
      label: "nbtasks"
      help: "nbtasks"
